import turtle
import random

def generate_random_color():
    color = "#{:06x}".format(random.randint(0, 0xFFFFFF))
    return color

car=turtle.Turtle()
car.speed(0)
turtle.title("SUV")

def draw_car(i,j,rand_hex_color):
    # upper body 
    car.color("grey")
    car.fillcolor(rand_hex_color)
    car.penup()
    car.goto(i,j)
    car.pendown()
    car.begin_fill()
    car.forward(400)
    car.left(90)
    car.forward(100)
    car.left(90)
    car.forward(400)
    car.left(90)
    car.forward(100)
    car.end_fill()

    # door
    car.penup()
    car.goto(i+100,100)
    car.pendown()
    car.setheading(40)
    car.forward(125)
    car.setheading(0)
    car.forward(200)
    car.setheading(-90)
    car.forward(80)
    car.setheading(90)
    car.penup()
    car.goto(200,50)
    car.pendown()
    car.forward(49.5)
    
    # windows
    car.penup()
    car.goto(i+200,100)
    car.pendown()
    car.setheading(90)
    car.forward(79)

    car.penup()
    car.goto(i+300,100)
    car.pendown()
    car.setheading(90)
    car.forward(79)

    # Seats
    car.fillcolor("#F5F5DC")
    car.begin_fill()
    car.penup()
    car.goto(i+170,100)    
    car.pendown()
    car.setheading(45)
    car.forward(70)
    car.setheading(0)
    car.forward(10)
    car.setheading(225)
    car.forward(70)
    car.end_fill()

    car.fillcolor("#F5F5DC")
    car.begin_fill()
    car.penup()
    car.goto(i+230,100)    
    car.pendown()
    car.setheading(45)
    car.forward(70)
    car.setheading(0)
    car.forward(10)
    car.setheading(225)
    car.forward(70)
    car.end_fill()

    car.fillcolor("#F5F5DC")
    car.begin_fill()
    car.penup()
    car.goto(i+280,100)    
    car.pendown()
    car.setheading(45)
    car.forward(70)
    car.setheading(0)
    car.forward(10)
    car.setheading(225)
    car.forward(70)
    car.end_fill()

    # wheels 
    car.penup()
    car.goto(200,150)
    car.pendown()
    car.color("black")
    car.fillcolor("black")
    car.begin_fill()
    car.circle(30)
    car.end_fill()
    car.penup()
    car.goto(-100,-10)
    car.pendown()
    car.color("black")
    car.fillcolor("black")
    car.begin_fill()
    car.circle(30)
    car.end_fill()

    car.penup()
    car.goto(100,-10)
    car.pendown()
    car.color("black")
    car.fillcolor("black")
    car.begin_fill()
    car.circle(30)
    car.end_fill()
    car.hideturtle()
    turtle.done()

rand_hex_color=generate_random_color()
draw_car(-200,0,rand_hex_color)


