import turtle
import random
import flower
import vehicles
# SUV information
suv = vehicles.SUV('Volvo', 2000, 30000, 18500.0, 5)

def generate_random_color():
    color = "#{:06x}".format(random.randint(0, 0xFFFFFF))
    return color


def draw_car(i, j, rand_hex_color, scale):
    # Draw car at specified position with specified scale
    car = turtle.Turtle()
    car.speed("fastest")
    # upper body 
    car.color("grey")
    car.fillcolor(rand_hex_color)
    car.penup()
    car.goto(i*scale,j*scale)
    car.pendown()
    car.begin_fill()
    car.forward(400*scale)
    car.left(90)
    car.forward(100*scale)
    car.left(90)
    car.forward(400*scale)
    car.left(90)
    car.forward(100*scale)
    car.end_fill()

    # door
    car.penup()
    car.goto((i+100)*scale,100*scale)
    car.pendown()
    car.setheading(40)
    car.forward(125*scale)
    car.setheading(0)
    car.forward(200*scale)
    car.setheading(-90)
    car.forward(80*scale)
    car.setheading(90)
    car.penup()
    car.goto(200*scale,50*scale)
    car.pendown()
    car.forward(49.5*scale)
    
    # windows
    car.penup()
    car.goto((i+200)*scale,100*scale)
    car.pendown()
    car.setheading(90)
    car.forward(79*scale)

    car.penup()
    car.goto((i+300)*scale,100*scale)
    car.pendown()
    car.setheading(90)
    car.forward(79*scale)

    # Seats
    # car.fillcolor("#F5F5DC")
    # car.begin_fill()
    # car.penup()
    # car.goto(i+0,100)    
    # car.pendown()
    # car.setheading(45)
    # car.forward(70)
    # car.setheading(0)
    # car.forward(10)
    # car.setheading(225)
    # car.forward(70)
    # car.end_fill()

    car.fillcolor("#F5F5DC")
    car.begin_fill()
    car.penup()
    car.goto((i+230)*scale,100*scale)    
    car.pendown()
    car.setheading(45)
    car.forward(70*scale)
    car.setheading(0)
    car.forward(10*scale)
    car.setheading(225)
    car.forward(70*scale)
    car.end_fill()

    car.fillcolor("#F5F5DC")
    car.begin_fill()
    car.penup()
    car.goto((i+300)*scale,100*scale)    
    car.pendown()
    car.setheading(45)
    car.forward(70*scale)
    car.setheading(0)
    car.forward(10*scale)
    car.setheading(225)
    car.forward(70*scale)
    car.end_fill()

    # wheels 
    car.penup()
    car.goto((200)*scale,150*scale)
    car.pendown()
    car.color("black")
    car.fillcolor("black")
    car.begin_fill()
    car.circle(30*scale)
    car.end_fill()
    car.penup()
    car.goto((-100)*scale,-10*scale)
    car.pendown()
    car.color("black")
    car.fillcolor("black")
    car.begin_fill()
    car.circle(30*scale)
    car.end_fill()

    car.penup()
    car.goto(100*scale,-10*scale)
    car.pendown()
    car.color("black")
    car.fillcolor("black")
    car.begin_fill()
    car.circle(30*scale)
    car.end_fill()
    car.hideturtle()
    # turtle.done()
    turtle.update()


# draw_car(-200,0,rand_hex_color)
# scale=random.uniform(0.1,0.3)
def main(): 
    turtle.title("SUV")
    turtle.tracer(0,0)#disable animation
    rand_hex_color=generate_random_color()
    scale=random.uniform(0.1,1)
    print(scale)
    flower.main()
    draw_car(-200,-20,rand_hex_color,scale)
    # SUV INFO DISPLAY 
    boldfont=("Arial",15,"bold")
    reg_font=("Times",12,"normal")

    turtle.penup()
    turtle.goto(-635,325)
    turtle.right(90)
    turtle.write("USED CAR INVENTORY",font=boldfont)
    turtle.goto(-635,315)
    turtle.write("*******************",font=boldfont)
    turtle.goto(-635,305)
    turtle.write("The following suv is in inventory",font=boldfont)
    turtle.goto(-635,285)
    turtle.write('Make:',font=boldfont)
    turtle.goto(-550,285)
    turtle.write(f"{suv.get_make()}",font=reg_font)
    turtle.goto(-635,265)
    turtle.write('Model:',font=boldfont)
    turtle.goto(-550,265)
    turtle.write(f'{suv.get_model()}',font=reg_font)
    turtle.goto(-635,245)
    turtle.write('Mileage:',font=boldfont)
    turtle.goto(-550,245)
    turtle.write(f'{suv.get_mileage()}',font=reg_font)
    turtle.goto(-635,225)
    turtle.write('Price:',font=boldfont)
    turtle.goto(-550,225)
    turtle.write(f'{suv.get_price()}',font=reg_font)
    turtle.goto(-635,205)
    turtle.write('Passenger Capacity:',font=boldfont)
    turtle.goto(-465,205)
    turtle.write(f'{suv.get_pass_cap()}',font=reg_font)
    turtle.update()
    turtle.done()


if __name__=="__main__":
    main()